### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by bil-elmoussaoui** [bil-elmoussaoui/StartupWMClassFixer#1]
- [x] Initial script using Python/Bash 
- [x] Initial Database 
- [x] Backup/Revert desktop files 
- [x] If `StartupWMClass` exists with a different value, change it instead of adding a new line
- [x] Update Readme

Example of database file : 
`desktop file name, startupwmclass value`

**Comment by bil-elmoussaoui** [comment]
@wa4557 Do you want to contribute on this? :) The script will add/update `StartupWMClass` propoerty in the desktop file of some application, to make the icons look right in a dash(Gnome)/Dock or when using `Alt + Tab`. Almost every steam game has this issue, and some of other application like Octave, Arduino IDE...

**Comment by wa4557** [comment]
Sure thing. I guess this might be an issue that is best solved using bash scripts. Python is a bit of an overkill here...

**Comment by wa4557** [comment]
I can provide the bash script (I actually have a bit more time now the next weeks:) But you have to tell me what I should do

**Comment by bil-elmoussaoui** [comment]
I'm going to use bash script

**Comment by bil-elmoussaoui** [comment]
Well, we should read the database file that will contain the application name, the desktop file name , and the startupWMclass value! For each file we should check in every desktop file location, `/usr/share/applications` and `.local/share/applications` we can get that from Hardcode-fixer i guess; and if the file do exists, we add the startupWMclass if the property does not exists; the script will need root permissions as some files do exists in `/usr/..`

**Comment by wa4557** [comment]
Ah ok, that should be fairly easy. Right now I'm working on the musseq icon but as soon as I'm finished with that I can work on the script. Do youu want to start or should I build from scratch. I guess it's ok if we just both work on it and upload the changes

**Comment by bil-elmoussaoui** [comment]
I will start working on it and upload the changes

**Comment by wa4557** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
@wa4557 I added the script :) We just need to implement restore/backup

**Comment by bil-elmoussaoui** [comment]
Done!

**Comment by bil-elmoussaoui** [comment]
@wa4557 If you have some free time, can you take a look at Readme file if everything is correct. Also the bash script as i'm not really used to it :P

**Comment by wa4557** [comment]
Wow that was fast:) we could implement a restore function by saving in the
database if and what was previously in startupwmclass and restore that
value if someone wants to revert

Bilal Elmoussaoui <notifications@github.com> schrieb am Sa., 21.11.2015,
12:32:

**Comment by bil-elmoussaoui** [comment]
I just copied the old file, is that good enough? i just need to add a ignore list for backup as we don't really need to backup desktop file that are in `$HOME/desktop/`

**Comment by wa4557** [comment]
I guess that's ok. A few things I'm going to fix however:

1. Remove the extension of the script. It's usually not considered good coding practice keeping the `.sh` extension. https://askubuntu.com/questions/503127/should-i-save-my-scripts-with-the-sh-extension

2. Backup files should be saved as `.bak` instead of `.backup`

3. If the file `database.csv` is not available we could `wget` it instead of exiting the script


Otherwise :+1:

**Comment by bil-elmoussaoui** [comment]
Good!!! :dancer:

**Comment by bil-elmoussaoui** [comment]
I use  `$(xdg-user-dir DESKTOP)` to get the directory of `$HOME/Desktop` (depends on the language the user's using) as we run the script as root we the result is `/home/root/Desktop/`, do you have any idea or an other way to do that?

**Comment by wa4557** [comment]
Hmm why do you need that folder?

**Comment by bil-elmoussaoui** [comment]
Steam creates desktop files there too

**Comment by wa4557** [comment]
That's tricky because in German for example the folder is called `Schreibtisch` so we cannot hardcode the name... We could replace `root` with `${SUDO_USER:-$USER}`?

**Comment by bil-elmoussaoui** [comment]
Good idea!! we will need to replace `/root/` with `/${SUDO_USER:-$USER}/` to avoid the case that user has a username like `rootblabla`! can you do that?

**Comment by wa4557** [comment]
Sure :)

**Comment by wa4557** [comment]
No that doesn't work :( The thing is that if i run `sudo xdg-user-dir DESKTOP` i get `/root/Desktop` but if I run `/home/andreas/Schreibtisch` so the name is also different...

**Comment by bil-elmoussaoui** [comment]
There's no way to run a code as an other user? :(

**Comment by wa4557** [comment]
`sudo -u ${SUDO_USER:-$USER} xdg-user-dir DESKTOP` should work

**Comment by bil-elmoussaoui** [comment]
Done :+1:

**Comment by wa4557** [comment]
:+1:
