### ISSUE TITLE
telegram-desktop's StartupWMClass changed

### ISSUE THREAD

**Issue by theel0ja** [bil-elmoussaoui/StartupWMClassFixer#12]
https://github.com/telegramdesktop/tdesktop/commit/2e6c15ff9d5112ac27b680687e93ec79f349855e

**Comment by bil-elmoussaoui** [comment]
Those changes are already released or still on master?

**Comment by theel0ja** [comment]
That's released in 1.0.26.

https://github.com/telegramdesktop/tdesktop/commits/v1.0.26

**Comment by bil-elmoussaoui** [comment]
Can you please open a PR to fix that ? Thanks
