### ISSUE TITLE
Some apps

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/StartupWMClassFixer#15]
App: `Goodvibes`
Desktop file: `com.elboulangero.Goodvibes.desktop`
Fix: `StartupWMClass=goodvibes`

App: `Gnome Terminal`
Desktop file: `gnome-terminal.desktop`
Fix: `StartupWMClass=gnome-terminal-server`

gnome-terminal  duplicate icon on Plank (on elementaryOS) without `StartupWMClass=gnome-terminal-server` also duplicate icon if enable option `OnlyShowIn=GNOME;Unity;`
Maybe need add option on script for comment out `OnlyShowIn` line

**Comment by bil-elmoussaoui** [comment]
For the OnlyShowIn, that should be a plank issue i guess

**Comment by varlesh** [comment]
But really it's stupid option,  i don't know why this needed

**Comment by bil-elmoussaoui** [comment]
I have added Goodvibes support. The Gnome Terminal issue is not about a missing StartupWMClass. It's due to OnlyShowIn. You can add Pantheon on the list. Or just report that upstream.  (Plank? or Gnome Terminal)
