### ISSUE TITLE
TeamViewer

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/StartupWMClassFixer#17]
- Application Name - `TeamViewer`
- Desktop file name - `com.teamviewer.TeamViewer`
- StartupWMClass - `TeamViewer`

NOTE: Also file `/usr/share/applications/com.teamviewer.TeamViewer.desktop` it's symlink to `/opt/teamviewer/tv_bin/desktop/com.teamviewer.TeamViewer.desktop`
https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/470

**Comment by bil-elmoussaoui** [comment]
TeamViewer already exists ....
https://github.com/bil-elmoussaoui/StartupWMClassFixer/blob/master/database.csv#L63

**Comment by bil-elmoussaoui** [comment]
We now, resolve the path link since 24efbd8d9bcb08c7791b819683d259cd4a9fc134
So it shouldn't be an issue anymore.
