### ISSUE TITLE
Suggestions...

### ISSUE THREAD

**Issue by KilrSabr** [bil-elmoussaoui/StartupWMClassFixer#2]
1. [x] There needs to be an option to automatically download the latest database file to the current directory (from the terminal or CLI) when setting up (or applying) this fix.

2. [x] Android Studio to be added to the database list.

...other than that it is a great idea and a cool 'fix'.
Cheers, KilrSabr.

**Comment by bil-elmoussaoui** [comment]
Thanks for your suggestions!
1 - I will add the update right now :) 
2 - Can you give me the desktop file name and the process name (you can see in the readme how to find it)

**Comment by bil-elmoussaoui** [comment]
Update added in my latest commit ,see the readme !

**Comment by KilrSabr** [comment]
Dude, you are fast.

I am new to this stuff - this is my first access to a GitHut account. 

Anyway...I will still read all the GitHut rules and guidelines, but to answer your immediate question.

The application details are as follows:
Application Name: Android Studio
Desktop File (Name): android-studio.desktop
Process Name: java    (but i am not sure if this is correct. I checked it with the Gnome System Monitor but couldn't identify it properly. I then used the 'top' command in the terminal and that is where I concluded that the process name is 'java'. This is the only application I was running at the time that could've returned this 'java' process indicator). But I will research it a little more on the internet and let you know if I come up with something different.

**Comment by bil-elmoussaoui** [comment]
Welcome to Github! :) What distro you're using ? elementary ?

**Comment by bil-elmoussaoui** [comment]
I added Android studio support, can you try again ?

**Comment by KilrSabr** [comment]
Yes, i am using elementary OS.

**Comment by bil-elmoussaoui** [comment]
Should work now.
