### ISSUE TITLE
StartupWMClass, where to look for clues

### ISSUE THREAD

**Issue by notfrombrooklyn** [bil-elmoussaoui/StartupWMClassFixer#5]
Hello. Can you tell where to look to see if there's a StartupWMClass problem?

By the way, thanks for the okular fix.

**Comment by bil-elmoussaoui** [comment]
Hello, 
I change the icon name of the application to something else and see if the icon is still the same (if you use Gnome you will need to restart Gnome-shell); open the application after that and use ALT + TAB to see the application icon, if the icon is looking blurry or not the same as the one you've just defined it's a StartupWMClass problem :+1: 
I hope i was clear :p 
And you're welcome

**Comment by notfrombrooklyn** [comment]
:) Yes, clear enough. Next time will know where to look.

**Comment by bil-elmoussaoui** [comment]
Or just open an issue here and i will fix it as soon as i can;)
