### ISSUE TITLE
Fix by icon theme symlinks?

### ISSUE THREAD

**Issue by palob** [bil-elmoussaoui/StartupWMClassFixer#7]
It looks like some applications can be fixed without editing ``.desktop`` files.

I recently introduced a symlink ``telegram-desktop.svg`` to Numix Circle.

This fixed the duplicate unthemed icon when running Telegram Desktop 
(``StartupWMClass=telegram-desktop``) for me.

However I wasn't successful with any other application. From what I experienced it doesn't work if the ``StartupWMClass`` isn't specified in the launcher which was the case for Krita, Okular, Octave, Spyder and GPS Prune.

**Comment by palob** [comment]
Hmm. maybe I was hallucinating, Telegram is back to the old state.

**Comment by bil-elmoussaoui** [comment]
Well, it's not about the icon line but the StartupWMClass. Even if symlinks can fix that, we can't know if the icon exists in the theme and which sizes are supported.. which makes the task just so hard :p

**Comment by palob** [comment]
I wonder if in cases where ``StartupWMClass=icon`` is set in the launcher a symlink ``icon.xxx`` fixes the icon.

But now that even Telegram is back to being unthemed, probably not. Maybe you can try with one?

**Comment by bil-elmoussaoui** [comment]
Yeah, in this case it should work! but not for all the themes, which is not perfect :(

**Comment by palob** [comment]
Yeah, just wondering whether something can be done from the Numix-Circle side.

**Comment by bil-elmoussaoui** [comment]
The script was created for adding the missing `StartupWMClass` keys to the desktop file, the best way to fix this is to report that to the application dev! 
For example Arduino is not behaving correctly, the first window will use the default StartupWMClass but the second window will use an other one...
